# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/iso" =
    { device = "/dev/disk/by-uuid/1980-01-01-00-00-00-00";
      fsType = "iso9660";
    };

  fileSystems."/nix/.ro-store" =
    { device = "/iso/nix-store.squashfs";
      fsType = "squashfs";
      options = [ "loop" ];
    };

  fileSystems."/nix/.rw-store" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/nix/store" =
    { device = "overlay";
      fsType = "overlay";
    };

  fileSystems."/mnt" =
    { device = "/dev/disk/by-uuid/f5c35d73-9dc4-4f4d-85bf-50c41644c752";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/mnt/.snapshots" =
    { device = "/dev/disk/by-uuid/f5c35d73-9dc4-4f4d-85bf-50c41644c752";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/mnt/boot" =
    { device = "/dev/disk/by-uuid/7741-4E07";
      fsType = "vfat";
    };

  fileSystems."/mnt/home" =
    { device = "/dev/disk/by-uuid/f5c35d73-9dc4-4f4d-85bf-50c41644c752";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/mnt/nix" =
    { device = "/dev/disk/by-uuid/f5c35d73-9dc4-4f4d-85bf-50c41644c752";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/mnt/swap" =
    { device = "/dev/disk/by-uuid/f5c35d73-9dc4-4f4d-85bf-50c41644c752";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  fileSystems."/mnt/var" =
    { device = "/dev/disk/by-uuid/f5c35d73-9dc4-4f4d-85bf-50c41644c752";
      fsType = "btrfs";
      options = [ "subvol=@var" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u2u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0f1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
