---
version: "3"
services:
    jellyfin:
        image: lscr.io/linuxserver/jellyfin:latest
        container_name: jellyfin
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Sao_Paulo
            - UMASK_SET=022 #optional
            # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
            # - NVIDIA_VISIBLE_DEVICES=all
            # - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
            - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
            # - JELLYFIN_CACHE_DIR=/config/cache
            # - JELLYFIN_CONFIG_DIR=/config
            # - JELLYFIN_DATA_DIR=/sconfig/data/metadata
            # - JELLYFIN_LOG_DIR=/config/log
        volumes:
            # - /home/juca/Documents/docker/docker-configs/resources/jellyfin/config:/config
            # - /home/juca/Documents/docker/docker-configs/resources/jellyfin/web:/usr/share/jellyfin/web
            # - /home/juca/Documents/docker/docker-configs/resources/jellyfin/cache:/config/cache
            - /home/juca/Documents/docker/docker-configs/resources/jellyfin/config:/config
            # - /home/juca/Documents/docker/docker-configs/resources/jellyfin/transcode:/config/cache/transcodes
            # - /home/juca/Documents/docker/docker-configs/resources/jellyfin/metadata:/config/data/metadata
            # - /home/juca/Documents/docker/docker-configs/resources/jellyfin/logs:/config/log
            - nas1_movies:/data/movies1
            - nas1_tvshow:/data/tvshows1
            - nas1_animes_series:/data/animes1/series
            - nas1_animes_movies:/data/animes1/movies
            - nas2_tvshow:/data/tvshows2
            - nas2_movies:/data/movies2
            - nas2_animes_series:/data/animes2/series
            - nas2_animes_movies:/data/animes2/movies
            - /home/juca/Videos/Animes/series:/data/animes3/series
            - /home/juca/Videos/Animes/movies:/data/animes3/movies
        ports:
            - 8096:8096
            - 8920:8920 #optional
            - 7359:7359/udp #optional
            - 1900:1900/udp #optional
        mem_limit: 1500M
        mem_reservation: 400M
        cpus: 0.8
        devices:
            # - /dev/dri:/dev/dri
            - /dev/dri/renderD128:/dev/dri/renderD128
            - /dev/dri/card1:/dev/dri/card1
        restart: unless-stopped
volumes:
    nas1_movies:
        driver_opts:
            # type: cifs
            # device: //192.168.1.207/volume_1/Movies
            # o: "username=juca,password=200291,vers=1.0,uid=1000,gid=990"
            type: nfs
            device: ":/mnt/HD/HD_b2/Movies"
            o: "addr=192.168.1.207,rw,nfsvers=3,nolock,soft,nosuid,noacl"
    nas1_tvshow:
        driver_opts:
            # type: cifs
            # device: //192.168.1.207/volume_1/TvShows
            # o: "username=juca,password=200291,vers=1.0,uid=1000,gid=990"
            type: nfs
            device: ":/mnt/HD/HD_b2/TvShows"
            o: "addr=192.168.1.207,rw,nfsvers=3,nolock,soft,nosuid,noacl"
    nas1_animes_series:
        driver_opts:
            # type: cifs
            # device: //192.168.1.207/volume_1/Animes
            # o: "username=juca,password=200291,vers=1.0,uid=1000,gid=990"
            type: nfs
            device: ":/mnt/HD/HD_b2/Animes/Series"
            o: "addr=192.168.1.207,rw,nfsvers=3,nolock,soft,nosuid,noacl"
    nas1_animes_movies:
        driver_opts:
            # type: cifs
            # device: //192.168.1.207/volume_1/Animes
            # o: "username=juca,password=200291,vers=1.0,uid=1000,gid=990"
            type: nfs
            device: ":/mnt/HD/HD_b2/Animes/Movies"
            o: "addr=192.168.1.207,rw,nfsvers=3,nolock,soft,nosuid,noacl"
    nas2_movies:
        driver_opts:
            # type: cifs
            # device: //192.168.1.207/volume_2/Transmission/complete/Filmes
            # o: "username=juca,password=200291,vers=1.0,uid=1000,gid=990"
            type: nfs
            device: ":/mnt/HD/HD_a2/Transmission/Volume_2/Filmes"
            o: "addr=192.168.1.207,rw,nfsvers=3,nolock,soft,nosuid,noacl"
    nas2_tvshow:
        driver_opts:
            # type: cifs
            # device: //192.168.1.207/volume_2/Transmission/complete/Series
            # o: "username=juca,password=200291,vers=1.0,uid=1000,gid=990"
            type: nfs
            device: ":/mnt/HD/HD_a2/Transmission/Volume_2/Series"
            o: "addr=192.168.1.207,rw,nfsvers=3,nolock,soft,nosuid,noacl"
    nas2_animes_series:
        driver_opts:
            # type: cifs
            # device: //192.168.1.207/volume_2/Transmission/complete/Animes
            # o: "username=juca,password=200291,vers=1.0,uid=1000,gid=990"
            type: nfs
            device: ":/mnt/HD/HD_a2/Transmission/Volume_2/Animes/Series"
            o: "addr=192.168.1.207,rw,nfsvers=3,nolock,soft,nosuid,noacl"
    nas2_animes_movies:
        driver_opts:
            # type: cifs
            # device: //192.168.1.207/volume_2/Transmission/complete/Animes
            # o: "username=juca,password=200291,vers=1.0,uid=1000,gid=990"
            type: nfs
            device: ":/mnt/HD/HD_a2/Transmission/Volume_2/Animes/Movies"
            o: "addr=192.168.1.207,rw,nfsvers=3,nolock,soft,nosuid,noacl"
# networks:
#   default:
#     driver: bridge
#     # name: duckdns
#     name: media
#     external: true
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.12.0.0/16
