services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - UMASK_SET=022 #optional
      # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
      # - NVIDIA_VISIBLE_DEVICES=all
      # - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - /home/juca/docker/jellyfin/config:/config
      - nas1_movies:/data/movies
      - nas1_tvshow:/data/tvshows
      - nas1_animes_series:/data/animes/series
      - nas1_animes_movies:/data/animes/movies
      - nas2_tvshow:/data/tvshows2
      - nas2_movies:/data/movies2
      - nas2_animes_series:/data/animes2/series
      - nas2_animes_movies:/data/animes2/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    mem_limit: 1000M
    mem_reservation: 300M
    cpus: 0.8
    devices:
      # - /dev/dri:/dev/dri
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card1:/dev/dri/card1
    restart: unless-stopped
volumes:
  nas1_movies:
    driver_opts:
      # type: cifs
      # device: //192.168.2.200/volume_1/Movies
      # o: "username=juca,password=200291,vers=1.0,uid=1000,gid=990"
      type: nfs
      device: ":/mnt/HD/HD_b2/Movies"
      o: "addr=192.168.2.200,rw,nfsvers=3,nolock,soft,nosuid"
  nas1_tvshow:
    driver_opts:
      # type: cifs
      # device: //192.168.2.200/volume_1/TvShows
      # o: "username=juca,password=200291,vers=1.0,uid=1000,gid=990"
      type: nfs
      device: ":/mnt/HD/HD_b2/TvShows"
      o: "addr=192.168.2.200,rw,nfsvers=3,nolock,soft,nosuid"
  nas1_animes_series:
    driver_opts:
      # type: cifs
      # device: //192.168.2.200/volume_1/Animes
      # o: "username=juca,password=200291,vers=1.0,uid=1000,gid=990"
      type: nfs
      device: ":/mnt/HD/HD_b2/Animes/Series"
      o: "addr=192.168.2.200,rw,nfsvers=3,nolock,soft,nosuid"
  nas1_animes_movies:
    driver_opts:
      # type: cifs
      # device: //192.168.2.200/volume_1/Animes
      # o: "username=juca,password=200291,vers=1.0,uid=1000,gid=990"
      type: nfs
      device: ":/mnt/HD/HD_b2/Animes/Movies"
      o: "addr=192.168.2.200,rw,nfsvers=3,nolock,soft,nosuid"
  nas2_movies:
    driver_opts:
      # type: cifs
      # device: //192.168.2.200/volume_2/Transmission/complete/Filmes
      # o: "username=juca,password=200291,vers=1.0,uid=1000,gid=990"
      type: nfs
      device: ":/mnt/HD/HD_a2/Transmission/Volume_2/Filmes"
      o: "addr=192.168.2.200,rw,nfsvers=3,nolock,soft,nosuid"
  nas2_tvshow:
    driver_opts:
      # type: cifs
      # device: //192.168.2.200/volume_2/Transmission/complete/Series
      # o: "username=juca,password=200291,vers=1.0,uid=1000,gid=990"
      type: nfs
      device: ":/mnt/HD/HD_a2/Transmission/Volume_2/Series"
      o: "addr=192.168.2.200,rw,nfsvers=3,nolock,soft,nosuid"
  nas2_animes_series:
    driver_opts:
      # type: cifs
      # device: //192.168.2.200/volume_2/Transmission/complete/Animes
      # o: "username=juca,password=200291,vers=1.0,uid=1000,gid=990"
      type: nfs
      device: ":/mnt/HD/HD_a2/Transmission/Volume_2/Animes/Series"
      o: "addr=192.168.2.200,rw,nfsvers=3,nolock,soft,nosuid"
  nas2_animes_movies:
    driver_opts:
      # type: cifs
      # device: //192.168.2.200/volume_2/Transmission/complete/Animes
      # o: "username=juca,password=200291,vers=1.0,uid=1000,gid=990"
      type: nfs
      device: ":/mnt/HD/HD_a2/Transmission/Volume_2/Animes/Movies"
      o: "addr=192.168.2.200,rw,nfsvers=3,nolock,soft,nosuid"
  # hd700_animes_series:
  #     driver_opts:
  #         type: cifs
  #         device: //192.168.2.1/HD700/Animes/Series
  #         # o: "username=root,password=200291,vers=3.1.1"
  #         o: "rw,guest"
  # hd700_animes_movies:
  #     driver_opts:
  #         type: cifs
  #         device: //192.168.2.1/HD700/Animes/Movies
  #         o: "rw,guest"
  # hd700_movies:
  #     driver_opts:
  #         type: cifs
  #         device: //192.168.2.1/HD700/Movies
  #         o: "rw,guest"
  # hd700_tvshows:
  #     driver_opts:
  #         type: cifs
  #         device: //192.168.2.1/HD700/Tvshows
  #         o: "rw,guest"
# networks:
#   default:
#     driver: bridge
#     # name: duckdns
#     name: media
#     external: true
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.12.0.0/16
