services:
  jellyfin:
    #image: lscr.io/linuxserver/jellyfin:arm64v8-nightly-2025021314ubu2404-ls62
    image: lscr.io/linuxserver/jellyfin:10.10.7
    container_name: jellyfin
    privileged: true
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Sao_Paulo
    volumes:
      # - /root/docker/jellyfin/config:/config
      # - /root/docker/jellyfin/cache:/cache
      - /opt/docker/composes/jellyfin/data:/config
      - /opt/docker/composes/jellyfin/cache:/cache

      # - externalHD_movies:/filmes
      - /mnt/700gb/Movies:/filmes
      # - externalHD_series:/series
      - /mnt/700gb/Tvshows:/series
      # - externalHD_animes:/animes
      - /mnt/700gb/Animes:/animes
      - nas1_movies:/filmes1
      - nas1_tvshow:/series1
      - nas1_animes:/animes1
      - nas2_tvshow:/series2
      - nas2_movies:/filmes2
      - nas2_animes:/animes2

      # - /etc/OpenCL:/etc/OpenCL:ro # only required to enable OpenCL-accelerated HDR -> SDR tonemapping
      # - /usr/lib/aarch64-linux-gnu/libmali.so.1:/usr/lib/aarch64-linux-gnu/libmali.so.1:ro # only required to enable OpenCL-accelerated HDR -> SDR tonemapping
    # security_opt:
    #   - systempaths=unconfined
    #   - apparmor=unconfined
    ports:
      - 3545:8096
      # - 8920:8920 #optional
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    mem_limit: 1600M # 1500M
    # mem_reservation: 300M
    cpus: 1.5
    networks:
      media:
    # network_mode: "bridge" # "host"
    devices:
      ### Intel
      # - /dev/dri:/dev/dri
      # - /dev/dri/renderD128:/dev/dri/renderD128
      # - /dev/dri/card1:/dev/dri/card1

      ### Rockchip
      - /dev/rga:/dev/rga
      - /dev/dri:/dev/dri
      #- /dev/dri/card0:/dev/dri/card0
      #- /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dma_heap:/dev/dma_heap
      - /dev/mpp_service:/dev/mpp_service
      #- /dev/mali0:/dev/mali0 # only required to enable OpenCL-accelerated HDR -> SDR tonemapping
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    restart: unless-stopped
volumes:
  hd700_animes:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username=guest,vers=3.0,uid=1000,gid=1000,file_mode=0777,dir_mode=0777"
      device: "//10.10.10.1/700gb/Animes"
  hd700_movies:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username=guest,vers=3.0,uid=1000,gid=1000,file_mode=0777,dir_mode=0777"
      device: "//10.10.10.1/700gb/Movies"
  hd700_series:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username=guest,vers=3.0,uid=1000,gid=1000,file_mode=0777,dir_mode=0777"
      device: "//10.10.10.1/700gb/Tvshows"
  nas1_movies:
    driver_opts:
      type: nfs
      device: :/mnt/HD/HD_b2/Movies
      o: addr=10.10.10.226,rw,nfsvers=3,nolock,nosuid,noexec,nodev
  nas1_tvshow:
    driver_opts:
      type: nfs
      device: :/mnt/HD/HD_b2/TvShows
      o: addr=10.10.10.226,rw,nfsvers=3,nolock,nosuid,noexec,nodev
  nas1_animes:
    driver_opts:
      type: nfs
      device: :/mnt/HD/HD_b2/Animes
      o: addr=10.10.10.226,rw,nfsvers=3,nolock,nosuid,noexec,nodev
  nas2_movies:
    driver_opts:
      type: nfs
      device: :/mnt/HD/HD_a2/Transmission/Volume_2/Filmes
      o: addr=10.10.10.226,rw,nfsvers=3,nolock,nosuid,noexec,nodev
  nas2_tvshow:
    driver_opts:
      type: nfs
      device: :/mnt/HD/HD_a2/Transmission/Volume_2/Series
      o: addr=10.10.10.226,rw,nfsvers=3,nolock,nosuid,noexec,nodev
  nas2_animes:
    driver_opts:
      type: nfs
      device: :/mnt/HD/HD_a2/Transmission/Volume_2/Animes
      o: addr=10.10.10.226,rw,nfsvers=3,nolock,nosuid

networks:
  media:
    name: my-bridge-net
    external: true

  # hd700_animes_series:
  #     driver_opts:
  #         type: cifs
  #         device: //192.168.2.1/HD700/Animes/Series
  #         # o: "username=root,password=200291,vers=3.1.1"
  #         o: "rw,guest"
  # hd700_animes_movies:
  #     driver_opts:
  #         type: cifs
  #         device: //192.168.2.1/HD700/Animes/Movies
  #         o: "rw,guest"
  # hd700_movies:
  #     driver_opts:
  #         type: cifs
  #         device: //192.168.2.1/HD700/Movies
  #         o: "rw,guest"
  # hd700_tvshows:
  #     driver_opts:
  #         type: cifs
  #         device: //192.168.2.1/HD700/Tvshows
  #         o: "rw,guest"
# networks:
#   default:
#     driver: bridge
#     # name: duckdns
#     name: media
#     external: true
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.12.0.0/16

# docker volume rm jellyfin_hd700_animes_movies jellyfin_hd700_animes_series jellyfin_hd700_movies jellyfin_hd700_tvshows jellyfin_nas1_animes_movies jellyfin_nas1_animes_series jellyfin_nas1_movies jellyfin_nas1_tvshow jellyfin_nas2_animes_movies jellyfin_nas2_animes_series jellyfin_nas2_movies jellyfin_nas2_tvshow
