services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.10.7
    container_name: jellyfin_media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - UMASK_SET=022 #optional
    privileged: true
    volumes:
      #- /root/docker/transmission/data:/config
      - /home/juca/services/jellyfin/data:/config

      - smb-animes:/animes
      - smb-downloads:/downloads
      - smb-series:/series
      - smb-movies:/filmes
      - smb-livros:/livros
      - smb-mangas:/mangas
      - smb-cursos:/cursos

      - nas1_movies:/filmes1
      - nas1_tvshow:/series1
      - nas1_animes:/animes1
      - nas2_movies:/filmes2
      - nas2_tvshow:/series2
      - nas2_animes:/animes2
      - nas2_downloads:/downloads2
      - nas2_cursos:/cursos2
    ports:
      - 3545:8096
      # - 8920:8920 #optional
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    devices:
      ### Rockchip
      - /dev/rga:/dev/rga
      - /dev/dri:/dev/dri
      # - /dev/dri/card0:/dev/dri/card0
      # - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dma_heap:/dev/dma_heap
      - /dev/mpp_service:/dev/mpp_service
      - /dev/mali0:/dev/mali0 # only required to enable OpenCL-accelerated HDR -> SDR tonemapping
    restart: unless-stopped
volumes:
  smb-animes:
    driver_opts:
      type: cifs
      o: "guest,vers=2.1,nounix,uid=1000,gid=1000,sec=none"
      device: //10.10.10.1/700gb/Animes
  smb-downloads:
    driver_opts:
      type: cifs
      o: "guest,vers=2.1,nounix,uid=1000,gid=1000,sec=none"
      device: //10.10.10.1/700gb/Downloads
  smb-series:
    driver_opts:
      type: cifs
      o: "guest,vers=2.1,nounix,uid=1000,gid=1000,sec=none"
      device: //10.10.10.1/700gb/Tvshows
  smb-livros:
    driver_opts:
      type: cifs
      o: "guest,vers=2.1,nounix,uid=1000,gid=1000,sec=none"
      device: //10.10.10.1/700gb/Books
  smb-movies:
    driver_opts:
      type: cifs
      o: "guest,vers=2.1,nounix,uid=1000,gid=1000,sec=none"
      device: "//10.10.10.1/700gb/Movies"
  smb-mangas:
    driver_opts:
      type: cifs
      o: "guest,vers=2.1,nounix,uid=1000,gid=1000,sec=none"
      device: "//10.10.10.1/700gb/Mangas"
  smb-cursos:
    driver: local
    driver_opts:
      type: "cifs"
      o: "guest,vers=2.1,nounix,uid=1000,gid=1000,sec=none"
      # device: //10.10.10.1/700gb/Cursos
      device: "//10.10.10.1/700gb/Cursos"
  nas1_movies:
    driver_opts:
      type: nfs
      device: :/mnt/HD/HD_b2/Movies
      o: addr=10.10.10.10,rw,nfsvers=3,nolock,nosuid,noexec,nodev
  nas1_tvshow:
    driver_opts:
      type: nfs
      device: :/mnt/HD/HD_b2/TvShows
      o: addr=10.10.10.10,rw,nfsvers=3,nolock,nosuid,noexec,nodev
  nas1_animes:
    driver_opts:
      type: nfs
      device: :/mnt/HD/HD_b2/Animes
      o: addr=10.10.10.10,rw,nfsvers=3,nolock,nosuid,noexec,nodev
  nas2_movies:
    driver_opts:
      type: nfs
      device: :/mnt/HD/HD_a2/Transmission/Volume_2/Filmes
      o: addr=10.10.10.10,rw,nfsvers=3,nolock,nosuid,noexec,nodev
  nas2_tvshow:
    driver_opts:
      type: nfs
      device: :/mnt/HD/HD_a2/Transmission/Volume_2/Series
      o: addr=10.10.10.10,rw,nfsvers=3,nolock,nosuid,noexec,nodev
  nas2_animes:
    driver_opts:
      type: nfs
      device: :/mnt/HD/HD_a2/Transmission/Volume_2/Animes
      o: addr=10.10.10.10,rw,nfsvers=3,nolock,nosuid
  nas2_downloads:
    driver_opts:
      type: nfs
      device: :/mnt/HD/HD_a2/Transmission/Volume_2/Downloads
      o: addr=10.10.10.10,rw,nfsvers=3,nolock,nosuid
  nas2_cursos:
    driver_opts:
      type: nfs
      device: :/mnt/HD/HD_a2/Transmission/Volume_2/Cursos
      o: addr=10.10.10.10,rw,nfsvers=3,nolock,nosuid
