---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.9.11
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - UMASK_SET=022 #optional
    volumes:
      - /root/docker-composes/jellyfin/config:/config
      - /root/docker-composes/jellyfin/cache:/cache
      - nas1_movies:/data/movies
      - nas1_tvshow:/data/tvshows
      - nas1_animes:/data/animes
      - nas2_tvshow:/data/tvshows2
      - nas2_movies:/data/movies2
      - nas2_animes:/data/animes2

    ports:
      - 3545:8096
      # - 8920:8920 #optional
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    mem_limit: 850M # 1500M
    # mem_reservation: 300M
    cpus: 1.4
    network_mode: "host"
    devices:
      ### Intel
      # - /dev/dri:/dev/dri
      # - /dev/dri/renderD128:/dev/dri/renderD128
      # - /dev/dri/card1:/dev/dri/card1

      ### Rockchip
      - /dev/rga:/dev/rga
      - /dev/dri:/dev/dri
      # - /dev/dri/card0:/dev/dri/card0
      # - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dma_heap:/dev/dma_heap
      - /dev/mpp_service:/dev/mpp_service
      # - /dev/mali0:/dev/mali0 # only required to enable OpenCL-accelerated HDR -> SDR tonemapping
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    restart: unless-stopped
volumes:
  nas1_movies:
    driver_opts:
      # type: cifs
      # device: //10.10.10.200/volume_1/Movies
      # o: "username=juca,password=200291,vers=1.0,uid=1000,gid=990"
      type: nfs
      device: ":/mnt/HD/HD_b2/Movies"
      o: "addr=10.10.10.200,rw,nfsvers=3,nolock,soft,nosuid"
  nas1_tvshow:
    driver_opts:
      type: nfs
      device: ":/mnt/HD/HD_b2/TvShows"
      o: "addr=10.10.10.200,rw,nfsvers=3,nolock,soft,nosuid"
  nas1_animes:
    driver_opts:
      type: nfs
      device: ":/mnt/HD/HD_b2/Animes"
      o: "addr=10.10.10.200,rw,nfsvers=3,nolock,soft,nosuid"
  nas2_movies:
    driver_opts:
      type: nfs
      device: ":/mnt/HD/HD_a2/Transmission/Volume_2/Filmes"
      o: "addr=10.10.10.200,rw,nfsvers=3,nolock,soft,nosuid"
  nas2_tvshow:
    driver_opts:
      type: nfs
      device: ":/mnt/HD/HD_a2/Transmission/Volume_2/Series"
      o: "addr=10.10.10.200,rw,nfsvers=3,nolock,soft,nosuid"
  nas2_animes:
    driver_opts:
      type: nfs
      device: ":/mnt/HD/HD_a2/Transmission/Volume_2/Animes"
      o: "addr=10.10.10.200,rw,nfsvers=3,nolock,soft,nosuid"

  # hd700_animes_series:
  #     driver_opts:
  #         type: cifs
  #         device: //192.168.2.1/HD700/Animes/Series
  #         # o: "username=root,password=200291,vers=3.1.1"
  #         o: "rw,guest"
  # hd700_animes_movies:
  #     driver_opts:
  #         type: cifs
  #         device: //192.168.2.1/HD700/Animes/Movies
  #         o: "rw,guest"
  # hd700_movies:
  #     driver_opts:
  #         type: cifs
  #         device: //192.168.2.1/HD700/Movies
  #         o: "rw,guest"
  # hd700_tvshows:
  #     driver_opts:
  #         type: cifs
  #         device: //192.168.2.1/HD700/Tvshows
  #         o: "rw,guest"
# networks:
#   default:
#     driver: bridge
#     # name: duckdns
#     name: media
#     external: true
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.12.0.0/16

# docker volume rm jellyfin_hd700_animes_movies jellyfin_hd700_animes_series jellyfin_hd700_movies jellyfin_hd700_tvshows jellyfin_nas1_animes_movies jellyfin_nas1_animes_series jellyfin_nas1_movies jellyfin_nas1_tvshow jellyfin_nas2_animes_movies jellyfin_nas2_animes_series jellyfin_nas2_movies jellyfin_nas2_tvshow
