# # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
# services:
#   pihole:
#     container_name: pihole
#     image: pihole/pihole:latest
#     # ports:
#       # DNS Ports
#       #- 53:53/tcp
#       #- 53:53/udp
#       # Default HTTP Port
#       #- 80:80/tcp
#       # Default HTTPs Port. FTL will generate a self-signed certificate
#       #- 443:443/tcp
#       # Uncomment the line below if you are using Pi-hole as your DHCP server
#       #- "67:67/udp"
#       # Uncomment the line below if you are using Pi-hole as your NTP server
#       #- "123:123/udp"
#     environment:
#       # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
#       TZ: America/Sao_Paulo
#       # Set a password to access the web interface. Not setting one will result in a random password being assigned
#       FTLCONF_webserver_api_password: 200291
#       # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
#       FTLCONF_dns_listeningMode: all
#     # Volumes store your data between container upgrades
#     volumes:
#       # For persisting Pi-hole's databases and common configuration file
#       - '/opt/docker/composes/files/pihole/etc-pihole:/etc/pihole'
#       - '/opt/docker/composes/files/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
#       - '/opt/docker/composes/files/pihole/var-log/:/var/log'
#       - '/opt/docker/composes/files/pihole/etc-cont-init.d/10-fixroutes.sh:/etc/cont-init.d/10-fixroutes.sh'
#       # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
#       #- './etc-dnsmasq.d:/etc/dnsmasq.d'
#     cap_add:
#       # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
#       # Required if you are using Pi-hole as your DHCP server, else not needed
#       - NET_ADMIN
#       # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
#       #- SYS_TIME
#       # Optional, if Pi-hole should get some more processing time
#       #- SYS_NICE
#     restart: unless-stopped
#     networks:
#       internal:
#       lan:
#         ipv4_address: 10.10.10.3
# networks:
#   internal:
#   lan:
#     name: lan
#     driver: macvlan
#     driver_opts:
#       parent: br-lan.20
#     ipam:
#       config:
#         - subnet: 10.10.10.0/24


services:
  pihole:
    container_name: piholev6
    image: pihole/pihole:latest
    hostname: piholev6
    networks:
      piholev6-net:
        ipv4_address: 10.10.10.192    #Change to your IP address in your network, make sure macvlan network is created.
      piholeunbound-net:
    environment:
      TZ: 'America/Sao_Paulo'
      FTLCONF_webserver_api_password: '200291'
      FTLCONF_dns_upstreams: 'unbound#5335'
    volumes:
      - '/root/composes/pi-hole/piholev6/etc/pihole:/etc/pihole'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    depends_on:
      - unbound

  unbound:
    image: alpinelinux/unbound:latest
    container_name: unbound
    networks:
      - piholeunbound-net
    volumes:
      - '/root/composes/pi-hole/piholev6/etc/unbound:/etc/unbound'
    restart: unless-stopped

networks:
  piholev6-net:
    name: macvlan_net
    external: true
  piholeunbound-net:
    name: piholeunbound-net

# networks:
#   piholev6-net:
#     name: local-network
#     driver: macvlan
#     driver_opts:
#       parent: br-lan.20
#     ipam:
#       config:
#         - gateway: 10.10.10.1
#           subnet: 10.10.10.0/24
#           ip_range: 10.10.10.20/32
#           # aux_addresses:
#           #   host: 10.10.10.20
#   piholeunbound-net:
#     name: my-bridge-net
#     driver: bridge
#     external: true
