services:
  portainer-ce:
    image: "portainer/portainer-ce:alpine"
    container_name: portainer
    ## Docker
    # command: -H unix:///var/run/docker.sock

    volumes:
      ## Docker
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/juca/services/portainer/data:/data"

    # network_mode: "host"

    ports:
      # https
      - "2221:8000"
      - "2222:9443"
      # http
      - "2220:9000"
    restart: unless-stopped
