---
services:
  portainer-ce:
    image: "portainer/portainer-ce:alpine"
    container_name: portainer
    ## Docker
    # command: -H unix:///var/run/docker.sock

    volumes:
      ## Docker
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/root/docker/portainer/data:/data"

    # network_mode: "host"

    ports:
      # https
      - "7080:8000"
      - "9555:9443"
      # http
      - "7081:9000"
    restart: unless-stopped
